import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { CheckUser } from "@/lib/getUser";
import TopBar from "../components/topbar/topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user_string } = await CheckUser();
  return (
    <ClerkProvider>
      <html lang="en">
        <TopBar userString={user_string} />
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
